services:
  phily-web:
    container_name: phily-container
    image: phily-latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    environment:
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
  nginx:
    image: nginx:alpine
    container_name: nginx
    expose:
      - "80"
      - "443"
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email "rodrigo.mardones.a@usach.cl" -d "phily.cl" -d "www.phily.cl" --agree-tos