version: '3.9'
services:
  phily-web:
    container_name: phily-container
    image: phily-latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    environment:
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - phily-web