version: '3.9'
services:
  phily-web:
    container_name: phily-container
    image: phily-latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    environment:
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}