version: '3.9'
services:
  phily-web:
    container_name: phily-container
    image: phily-latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    environment:
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
  certbot:
    image: certbot/certbot:latest
    volumes:
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - phily-web