import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <button className="btn btn-primary">One</button>
          <button className="btn btn-secondary">Two</button>
          <button className="btn btn-accent btn-outline">Three</button>
        </div>
      </main>
    </>
  )
}
